host:
  transport:
    protocol: TCP
    address: 127.0.0.1:0
    fixedpublicaddress: ""
  infinitybootstrap: false
  mintimeout: 1
  maxtimeout: 60
  timeoutmult: 2
  signmessages: false
  handshakesessionttl: 5000
service:
  skip: 10
  cachedirectory: network_cache
ledger:
  storage:
    datadirectory: ./data
    txretriesonconflict: 3
  pulsemanager:
    splitthreshold: 1000
  lightchainlimit: 5
  exporter:
    exportlag: 40
  pendingrequestslimit: 1000
log:
  level: debug
  adapter: zerolog
  formatter: text
metrics:
  listenaddress: 0.0.0.0:9090
  namespace: insolar
  zpagesenabled: true
  reportingperiod: 0s
logicrunner:
  rpclisten: 127.0.0.1:7778
  rpcprotocol: tcp
  builtin: {}
  goplugin:
    runnerlisten: 127.0.0.1:7777
    runnerprotocol: tcp
apirunner:
  address: localhost:19101
  call: /api/call
  rpc: /api/rpc
  timeout: 15
pulsar:
  connectiontype: tcp
  mainlisteneraddress: 127.0.0.1:58090
  storage:
    datadirectory: ./.artifacts/pulsar_data
    txretriesonconflict: 0
  pulsetime: 10000
  receivingsigntimeout: 1000
  receivingnumbertimeout: 1000
  receivingvectortimeout: 1000
  receivingsignsforchosentimeout: 0
  neighbours: []
  numberdelta: 10
  distributiontransport:
    protocol: TCP
    address: 127.0.0.1:58091
    fixedpublicaddress: ""
  pulsedistributor:
    bootstraphosts:
    - 127.0.0.1:13831
    - 127.0.0.1:23832
    - 127.0.0.1:33833
    - 127.0.0.1:43834
    - 127.0.0.1:53835
    pingrequesttimeout: 1000
    randomhostsrequesttimeout: 1000
    pulserequesttimeout: 1000
    randomnodescount: 5
versionmanager:
  minalowedversion: v0.3.0
keyspath: scripts/insolard/configs/bootstrap_keys.json
certificatepath: ""
tracer:
  jaeger:
    collectorendpoint: ""
    agentendpoint: 127.0.0.1:6831
    probabilityrate: 1
  samplingrules: {}
