language: go

# Faster container-based builds
sudo: false

go:
  - "1.11.x"

env:
  global:
    - CGO_ENABLED=0
    - GORACE="halt_on_error=1"
# «For parallel processes running at the same time, try to reduce the number. More than two to four processes should be fine, beyond that, resources are likely to be exhausted.»
# https://docs.travis-ci.com/user/common-build-problems/#my-build-script-is-killed-without-any-error
    - GOMAXPROCS=2
# debug logging by default
    - INSOLAR_LOG_LEVEL=debug

before_install:
  - make install-deps
install:
  - make pre-build
script:
# check if git repo unchanged in CI before build stage (try to catch forgotten generated files)
  - make test_git_no_changes
  - make build
  - make functest
  - make test_with_coverage

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
