# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
    "github.com/gogo/protobuf/protoc-gen-gogoslick",
    "github.com/gogo/protobuf/proto",
]

[[constraint]]
  version = "1.1.0"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/jbenet/go-base58"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ugorji/go"
  revision = "772ced7fd4c2f6322c07537a9a93b68d74551fa6"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.6.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.22.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/gofuzz"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.14.3"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  name = "github.com/insolar/x-crypto"
  version = "1.1.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.19.0"

[[constraint]]
  name = "github.com/fortytw2/leaktest"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gojuno/minimock"
  version="2.1.8"
