
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar-config
data:
  pulsar.yaml: |
    pulsar:
      connectiontype: tcp
      mainlisteneraddress: 0.0.0.0:58090
      storage:
        datadirectory: /opt/insolar/pulsar
        txretriesonconflict: 0
      pulsetime: 10000
      receivingsigntimeout: 1000
      receivingnumbertimeout: 1000
      receivingvectortimeout: 1000
      receivingsignsforchosentimeout: 0
      neighbours: []
      numberofrandomhosts: 1
      numberdelta: 10
      distributiontransport:
        protocol: TCP
        address: 0.0.0.0:58091
      pulsedistributor:
        bootstraphosts:
          - seed-0.bootstrap:7900
          - seed-1.bootstrap:7900
          - seed-2.bootstrap:7900
          - seed-3.bootstrap:7900
          - seed-4.bootstrap:7900
    keyspath: "/opt/insolar/config/bootstrap_keys.json"
    log:
      level: Debug
      adapter: zerolog
 
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pulsar
  labels:
    app: pulsar

spec:
  serviceName: pulsar
  replicas: 1
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      initContainers:
        - name: init-register
          imagePullPolicy: Never
          image: "base"
          tty: true
          stdin: true
          command: 
            - /bin/sh
            - -c
            - |
              /go/bin/insolar gen-key-pair > /opt/insolar/config/bootstrap_keys.json;
          env:
            - name: HOME
              value: /opt/insolar
          volumeMounts:
            - name: config
              mountPath: /opt/insolar/config
      containers:
        - name: pulsar
          imagePullPolicy: Never
          image: "base"
          workingDir: "/opt/insolar"
          tty: true
          stdin: true
          command: 
            - /go/bin/pulsard
            - -c
            - /opt/insolar/config/pulsar.yaml
          env:
            - name: HOME
              value: /opt/insolar
            - name: INSOLAR_KEYSPATH
              value: "/opt/insolar/config/bootstrap_keys.json"
            - name: INSOLAR_PULSAR_STORAGE_DATADIRECTORY
              value: "/opt/insolar/pulsar"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INSOLAR_PULSAR_MAINLISTENERADDRESS
              value: "$(POD_IP):58090"
            - name: INSOLAR_PULSAR_DISTRIBUTIONTRANSPORT_ADDRESS
              value: "$(POD_IP):58091"
          resources:
            requests:
              cpu: 300m
              memory: 200M
          volumeMounts:
            - name: config
              mountPath: /opt/insolar/config
            - name: pulsar
              mountPath: /opt/insolar/pulsar
            - name: code
              mountPath: /tmp/code
            - name: pulsar-config
              mountPath: /opt/insolar/config/pulsar.yaml
              subPath: pulsar.yaml
      volumes:
      - name: config
        emptyDir: {}
      - name: pulsar
        emptyDir: {}
      - name: code
        emptyDir: {}
      - name: pulsar-config
        configMap:
          name: pulsar-config
      imagePullSecrets:
      - name: registry-insolar-io
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel

